# ================================
# SERVER DETAILS
# ================================
spring.application.name=Microsite
server.port=8080
server.error.whitelabel.enabled=false
spring.mvc.throw-exception-if-no-handler-found=true
spring.main.allow-bean-definition-overriding=true
debug.mode=true

spring.datasource.url=jdbc:sqlserver://sql-server-ix-mfg-azure-dev.database.windows.net,1433;databaseName=ixmicrosite;encrypt=true;trustServerCertificate=true
#spring.datasource.url=jdbc:sqlserver://localhost;instanceName=SQLEXPRESS;databaseName=ixmicrosite;encrypt=true;trustServerCertificate=true
spring.datasource.username=DBAdmin
spring.datasource.password=@DB@se?@sswOrd
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# ================================
# USE CASE DEFAULTS
# ================================
usecase.default.status=DRAFT
usecase.default.page.size=10
usecase.default.sort.field=createdAt
usecase.default.sort.direction=DESC

# CORS Configuration
#cors.allowed-origins=__corsAllowedOrigins__
#cors.allowed-methods=GET,POST,PUT,DELETE,PATCH,OPTIONS
#cors.allowed-headers=*
