# ================================
# SERVER DETAILS
# ================================
spring.application.name=Microsite
server.port=443
server.error.whitelabel.enabled=false
spring.mvc.throw-exception-if-no-handler-found=true
spring.main.allow-bean-definition-overriding=true
debug.mode=true

#spring.datasource.url=jdbc:sqlserver://sql-server-ix-mfg-azure-dev.database.windows.net:1433;databaseName=ixmicrosite;encrypt=true;trustServerCertificate=true
#spring.datasource.url=jdbc:sqlserver://sql-server-ix-mfg-azure-dev.database.windows.net:1433;database=sql-db-ix-mfg-azure-dev;encrypt=true;trustServerCertificate=true
#spring.datasource.url=jdbc:sqlserver://localhost;instanceName=SQLEXPRESS;databaseName=ixmicrosite;encrypt=true;trustServerCertificate=true
spring.datasource.username=DBAdmin
spring.datasource.password=@DB@se?@sswOrd
spring.datasource.url=jdbc:sqlserver://sql-server-ix-mfg-azure-dev.database.windows.net:1433;database=sql-db-ix-mfg-azure-dev;encrypt=true;trustServerCertificate=true;
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true

# Hibernate performance tuning
spring.jpa.properties.hibernate.default_batch_fetch_size=20
spring.jpa.properties.hibernate.jdbc.batch_size=20

# ================================
# USE CASE DEFAULTS
# ================================
usecase.default.status=DRAFT
usecase.default.page.size=10
usecase.default.sort.field=createdAt
usecase.default.sort.direction=DESC

# ================================
# AZURE BLOB STORAGE
# ================================
azure.blob.container-name=ixmicrositelab
azure.blob.max-file-size-mb=250
spring.servlet.multipart.max-request-size=3GB
spring.servlet.multipart.max-file-size=250MB
azure.blob.chunk-size=8388608
storage.root.folder=usecase/artifacts
storage.path.artifacts.demo.videos=usecase/artifacts/Demo Videos/{usecase-id}
storage.path.artifacts.elevator_pitch=usecase/artifacts/Client Credentials/elevator_pitch/{usecase-id}
storage.path.artifacts.user_story=usecase/artifacts/Client Credentials/user_story/{usecase-id}
storage.path.artifacts.client.testimonials=usecase/artifacts/Client Testimonials/{usecase-id}
storage.path.banner_image=usecase/Banner URL/{usecase-id}
storage.path.thumbnail_image=usecase/Thumbnail URL/{usecase-id}
storage.path.industry_thumbnail=industry-thumbnail/{industry-id}
storage.path.hero_image=hero-image
storage.path.key_capacity=key-capacity
spring.servlet.multipart.enabled=true
server.tomcat.max-swallow-size=-1
server.tomcat.max-http-post-size=262144000
server.tomcat.max-http-form-post-size=262144000

# CORS Configuration
#cors.allowed-origins=__corsAllowedOrigins__
#cors.allowed-methods=GET,POST,PUT,DELETE,PATCH,OPTIONS
#cors.allowed-headers=*